### PR TITLE
Big number

### PR DESCRIPTION
**Pull request by dustinnorwood**
Fixes the problem with large negative numbers.

### CODE REVIEW

**Comment by th0114nd** [comment]
I think this deserves some test cases

**Comment by dustinnorwood** [comment]
Fair enough

**Comment by dustinnorwood** [comment]
On current develop, the test fails:
```  util tests
    1) converts negative numbers to and from hex


  0 passing (6ms)
  1 failing

  1) util tests converts negative numbers to and from hex:

      AssertionError: expected -2878439424 to equal -2070437967722283000
      + expected - actual

      --2878439424
      +-2070437967722283000
      
      at Context.<anonymous> (test/util.test.js:34:16)
```

**Comment by dustinnorwood** [comment]
On `big-number`:
```  util tests
    ✓ converts negative numbers to and from hex (164ms)


  1 passing (171ms)

```

**Pull request merged**
